# Simple deployment used to deploy and manage official Nginx Docker image. 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deploy-label
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec: 
      terminationGracePeriodSeconds: 1
      containers:
      - name: nginx-pod
        image: nginx:1.30.4
        imagePullPolicy: Always
        ports:
        - containerPort: 80
