apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-exporter
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
          name: http

    - name: nginx-prometheus-exporter
      image: nginx/nginx-prometheus-exporter:latest
      args:
        - -nginx.scrape-uri=http://127.0.0.1:80/stub_status
      ports:
        - containerPort: 9113
          name: metrics
